### ISSUE TITLE
Define vSphere Roles w/minimal set of privileges based on use case

### ISSUE THREAD

**Issue by ron1** [vmware/kubernetes#309]
/kind feature

Assume I have vCenter user, user1, which is used only for installing/upgrading kubernetes w/the vSphere Cloud Provider. Also assume I have an additional, less privileged vCenter user, user2, which is used by kubernetes w/the vSphere Cloud Provider at all other times. What is the minimal set of vCenter roles/privileges required by user2 for each of the following use cases?

1. Cluster supports only static persistent volume provisioning and all PVs are created with a Reclaim Reclaim Policy set to Retain
2. Cluster supports only static persistent volume provisioning and all PVs are created with a Reclaim Policy set to Delete
3. Cluster supports dynamic volume provisioning without storage policy based volume placement
4. Cluster supports dynamic volume provisioning with storage policy based volume placement

Table [](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#create-roles-add-privileges-to-roles-and-assign-them-to-the-vsphere-cloud-provider-user-and-vsphere-entities) currently describes the roles needed for use case 4 above.

In order to make these roles easy to use and easy to document, recommend that new names be defined for any newly introduced less-privileged roles required to support use cases 1-3 above. For example, operate-k8s-node-vms might be the new name for the first role in the table for use case 1. This role is w/out Privileges: "Resource.AssignVMToPool", "VirtualMachine.Inventory.Create", "VirtualMachine.Inventory.Delete" and w/out Entities: "Cluster", "Hosts".

If I define separate vCenter users as described above, I would like to assign role manage-k8s-node-vms to user1 and role operate-k8s-node-vms to user2. Distinguishing between these two different roles allows different roles to be used for different use cases.

Defining specific roles for specific use cases might help lower the barrier of entry for this technology into traditional environments that more tightly manage their vCenter credentials and privileges.

**Comment by shaominchen** [comment]
@ron1 The existing roles described in the documentation are all for *using* VCP features, not for *installing/uninstalling* VCP plugin itself. To install/uninstall VCP plugin, the required privileges are defined here: https://github.com/Kubernetes/Kubernetes-anywhere/blob/master/phase1/vsphere/README.md#prerequisites (this link is subject to change as we are moving away from kubernetes-anywhere to kubeadm)

Divyen and I discussed this, and we agree it might be useful to document some roles just as examples for some typical use cases. However, the existing roles defining minimal set of privileges required by VCP to interact with vCenter are still valid for the most common scenario where one single vSphere user will be defined and used by all kubernetes users. Please note that VCP only allows one user to be defined in vsphere.conf. To switch to a different user, you'll need to restart kubelet.

Alternatively, you can use kubernetes RBAC (https://kubernetes.io/docs/admin/authorization/rbac/) to achieve the same instead of relying on different vSphere users.

Anyway, we plan to add one more page to give some examples of different roles for different use cases. The existing roles description will remain unchanged. Please let us know if you have any comments or concerns.

**Comment by shaominchen** [comment]
The document has been updated: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#create-roles-add-privileges-to-roles-and-assign-them-to-the-vsphere-cloud-provider-user-and-vsphere-entities
