### ISSUE TITLE
Update VCP CI/CD to use kubeadm to configure k8s cluster for tests' execution

### ISSUE THREAD

**Issue by tusharnt** [vmware/kubernetes#348]
- [ ] Current setup deployed using kubernetes-anywhere uses older etcd version which needs to be fixed.
- [ ] Enable multi-master setup 
- [ ] Exercise UX script that configures VCP against a predeployed k8s cluster deployed using kubeadm.

**Comment by prashima** [comment]
Closing this issue.

- kubernetes-anywhere uses older etcd version: This is already fixed with new ignition image. The new tag is- https://hub.docker.com/r/cnastorage/etcd3-ignition/ 
- Multi master: tracked by https://github.com/vmware/kubernetes/issues/303
- UX script changes: not needed, https://github.com/vmware/kubernetes/issues/408 will take care of all CI/CD and testbed deployment tasks.
