### ISSUE TITLE
Octopus Testing - Make sure VCP correctly reports status of volumes if corresponding VC is down 

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#373]

**Comment by abrarshivani** [comment]
Manually Tested: Works as expected.

**Comment by shaominchen** [comment]
Test Steps (@abrarshivani to confirm):

1. Create a pod with dynamically created volume
2. Bring down the VC
3. Verify the volume is still attached to the pod
4. [TBD] Verify the error message returned by VCP to k8s
5. Restart VC

**Comment by prashima** [comment]
Moving this out of wonder woman, to make room for production code removal from test.

**Comment by BaluDontu** [comment]
Following are the test steps to be executed for this test:
- Create a pod with dynamically created volume
- Bring down the vpxd service on VC
- Verify the volume is still attached to the pod by executing SSH to the volume
- Start the vpxd service on VC
- Verify the volume is still attached to the pod by executing SSH to the volume

@prashima : Should we have hold off working on this test until your PR to remove production code removal from E2E tests is out?

**Comment by BaluDontu** [comment]
Below, I have mentioned very detailed instructions with references to code blocks on this can be done.

1. Create a pod with dynamically created volume
   - Create a vsphere volume - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/vsphere_volume_master_restart.go#L88
   - Create a pod spec with the above created vSphere volume - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/vsphere_volume_master_restart.go#L94. This pod spec should mount the volumes at specific location in the pod so that it will be easy to verify the volume is attached.
   - Create a pod with the podSpec retrieved above - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/vsphere_volume_master_restart.go#L102
   - Create empty file on the pod at the mounted volume location. You can refer the link for sample code - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/vsphere_volume_placement.go#L314.
2. Bring down the vpxd service on VC
   - You can bring down the vpxd service by remotely executing a command over SSH.
   - For this, create a method StopVpxdService() that accepts cmd and the VC ip. VC ip can be retrieved from test configuration file.
   - You can refer for a sample code at - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L3854. We need to create a test configuration variable that accepts VC USER name.
3. Verify the volume is still attached to the pod by executing SSH to the volume
   - Verify the volume is still attached to the pod after the vpxd service shut down.
   - Code block for reference - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/vsphere/vsphere_volume_placement.go#L321.
4. Start the vpxd service on VC
   - Start the vpxd service by executing a remote command over the VC ip. Follow the same instructions as in step 2 but this time the command would be the one to start the vpxd service.
5. Verify the volume is still attached to the pod by executing SSH to the volume
   - Verify the volume is still attached to the pod after the vpxd service is started again. This will make sure that the pod is still up and running.
   - Follow the instructions mentioned in step 3 for reference.

Inorder to execute the test, password less authentication needs to be setup between the test envt. and the VC.
