### ISSUE TITLE
Deprecated vm-uuid in vsphere.conf

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kubernetes#419]
If vmuuid is not present in the conf file and file ```/sys/class/dmi/id/product_serial``` is not present vcp throws an error.
Workaround (for multi-vc): Add some random uuid in the conf file since it is not used in code anywhere.

**Comment by prashima** [comment]
Putting it in backlog because we have a work around of putting fake uuid in conf file.

**Comment by prashima** [comment]
Putting this back in Wonder Women. Will let @abrarshivani decide if this needs to be moved out.

**Comment by BaluDontu** [comment]
@abrarshivani : We previously verified that all OS have `/sys/class/dmi/id/product_serial` file. Which OS did you use for testing?

**Comment by BaluDontu** [comment]
Based on discussion with @abrarshivani offline, this is the case with the latest commit for e2e test case support for multi-vc on PR - https://github.com/kubernetes/kubernetes/pull/57258.

The GetVsphere() function uses the newly implemented method newControllerNode() to create the vSphere struct for use by the e2e test cases. The code is present here - https://github.com/kubernetes/kubernetes/pull/57258/files#diff-0440866b50669702ddbd6ab73ec749e0R63. The newControllerNode() method tries to retrieve the vmUUID is not present in the configuration file. If we trigger our tests locally on Mac machines (but available in other Linux distributions), the file /sys/class/dmi/id/product_serial is not present locally. Because of this, e2e test cases cannot be executed on the local dev. environment.

The fix is to remove the check for vvmUUID in entirety from 1.9 branch - https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L378 as it is not longer needed. The NodeInfo object by default provides this information. I will have a PR out to fix this. This will

- Enable e2e test cases to be executed locally on Mac machines
- Remove unnecessary vmUUID code in 1.9 branch

**Comment by BaluDontu** [comment]
I have a PR out on kubernetes for fixing this issue - https://github.com/kubernetes/kubernetes/pull/58230

**Comment by BaluDontu** [comment]
The PR is merged. Closing this issue.
